# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchify < Formula
  desc "Orchify is an AI-powered orchestration platform. This CLI allows you to
run an Orchify local runtime so your own machine acts as an execution
runner for your workspace's AI agent jobs.
"
  homepage "https://github.com/orchify/orchify"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchify/orchify/releases/download/v0.0.7/orchify_0.0.7_darwin_amd64.tar.gz"
      sha256 "5af8f5cc37371f8845b7a4969554c16969a22b9011275754a2c92d7e930f042c"

      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchify/orchify/releases/download/v0.0.7/orchify_0.0.7_darwin_arm64.tar.gz"
      sha256 "e18b0a87aad1ae8e3b55a878300ffacdce6a0d9137afe81eb4fed06682a6f1c6"

      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify/releases/download/v0.0.7/orchify_0.0.7_linux_amd64.tar.gz"
      sha256 "ee64497e3fceb5b81bee17d5005e49d544e64393731e440cfccc770d061b0975"
      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify/releases/download/v0.0.7/orchify_0.0.7_linux_arm64.tar.gz"
      sha256 "4a3629b913c43c1168227b15616b3c8ab3b622574c9ecef4c9cfc5a44e5b617e"
      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  def caveats
    <<~EOS
      To run orchify as a background service with `brew services start orchify`,
      first authenticate once:

        orchify login

      Then set the following environment variables before starting the service:

        export ORCHIFY_API_BASE_URL=https://your-orchify-instance.example.com

      Alternatively, pass the flags directly:

        orchify start --api-base-url https://your-orchify-instance.example.com
    EOS
  end

  service do
    run [opt_bin/"orchify", "start",
         "--api-base-url", "#{ENV["ORCHIFY_API_BASE_URL"]}"]
    keep_alive true
    log_path var/"log/orchify.log"
    error_log_path var/"log/orchify.log"
  end

  test do
    system "#{bin}/orchify", "version"
  end
end
