# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchify < Formula
  desc "Orchify is an AI-powered orchestration platform. This CLI allows you to
run an Orchify local runtime so your own machine acts as an execution
runner for your workspace's AI agent jobs.
"
  homepage "https://github.com/orchify/orchify"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.10/orchify_0.0.10_darwin_amd64.tar.gz"
      sha256 "c662410cb2e698bf83aaa32540dde654ea51e3341fbcac9c9a14428e60d08fe8"

      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.10/orchify_0.0.10_darwin_arm64.tar.gz"
      sha256 "96e35e26b7877caa8dc65ff8f5007f1ddb45c8e6e1a619c3e4f7420387363fe3"

      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.10/orchify_0.0.10_linux_amd64.tar.gz"
      sha256 "469f59a824750ae270c6beb927799139dd213d1c58af1218863ed7cfd6328d19"
      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.10/orchify_0.0.10_linux_arm64.tar.gz"
      sha256 "64a60d5c9a6c007d28bd1e3f674a6486512c0ea94c269ccf94e45c75fe3f65ff"
      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  def caveats
    <<~EOS
      To run orchify as a background service with `brew services start orchify`,
      first authenticate once:

        orchify login

      Then set the following environment variables before starting the service:

        export ORCHIFY_API_BASE_URL=https://your-orchify-instance.example.com

      Alternatively, pass the flags directly:

        orchify start --api-base-url https://your-orchify-instance.example.com
    EOS
  end

  service do
    run [opt_bin/"orchify", "start",
         "--api-base-url", "#{ENV["ORCHIFY_API_BASE_URL"]}"]
    keep_alive true
    log_path var/"log/orchify.log"
    error_log_path var/"log/orchify.log"
  end

  test do
    system "#{bin}/orchify", "version"
  end
end
