# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchify < Formula
  desc "Orchify is an AI-powered orchestration platform. This CLI allows you to
run an Orchify local runtime so your own machine acts as an execution
runner for your workspace's AI agent jobs.
"
  homepage "https://github.com/orchify/orchify"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.8/orchify_0.0.8_darwin_amd64.tar.gz"
      sha256 "0adc2e93631cf90930611ab2c760952a8e56bf479969e6774b7de4b67afc0364"

      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.8/orchify_0.0.8_darwin_arm64.tar.gz"
      sha256 "32d8c78f8a6704e802a33de7eb198585758b1c78b069d3e2e14b7ee9ddcd87cf"

      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.8/orchify_0.0.8_linux_amd64.tar.gz"
      sha256 "e599d067311835a53395d3746bdbdd307eb6c101df39d61527323803e2a31f1d"
      define_method(:install) do
        bin.install "orchify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchify/orchify-cli/releases/download/v0.0.8/orchify_0.0.8_linux_arm64.tar.gz"
      sha256 "4fc34236bcc7fe99bb753795b96d51854abc2bd93970ee06a02ca58a5d972b19"
      define_method(:install) do
        bin.install "orchify"
      end
    end
  end

  def caveats
    <<~EOS
      To run orchify as a background service with `brew services start orchify`,
      first authenticate once:

        orchify login

      Then set the following environment variables before starting the service:

        export ORCHIFY_API_BASE_URL=https://your-orchify-instance.example.com

      Alternatively, pass the flags directly:

        orchify start --api-base-url https://your-orchify-instance.example.com
    EOS
  end

  service do
    run [opt_bin/"orchify", "start",
         "--api-base-url", "#{ENV["ORCHIFY_API_BASE_URL"]}"]
    keep_alive true
    log_path var/"log/orchify.log"
    error_log_path var/"log/orchify.log"
  end

  test do
    system "#{bin}/orchify", "version"
  end
end
